# Generated by Django 5.1.2 on 2024-12-19 13:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='region.region')),
            ],
            options={
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['name'], name='itinary_iti_name_3b8914_idx'), models.Index(fields=['region'], name='itinary_iti_region__5db7ce_idx'), models.Index(fields=['boundary'], name='itinary_iti_boundar_dc514b_idx')],
            },
        ),
    ]
