# Generated by Django 5.1.2 on 2024-12-19 13:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinary',
            name='boundary',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
