# Generated by Django 5.1.2 on 2025-01-03 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinary', '0002_alter_itinary_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinary',
            name='block_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
