# Generated by Django 5.1.2 on 2024-11-19 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinary', '0002_itinary_region'),
        ('region', '0004_region_region_regi_name_df1a77_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinary',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='region.region'),
        ),
    ]
