# Generated by Django 5.1.2 on 2025-01-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinary', '0003_itinary_block_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinary',
            name='block_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
