# Generated by Django 5.1.2 on 2024-11-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinary', '0003_alter_itinary_region'),
        ('region', '0005_rename_geojson_area_region_boundary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinary',
            old_name='geojson_area',
            new_name='boundary',
        ),
        migrations.AlterField(
            model_name='itinary',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='itinary',
            index=models.Index(fields=['region'], name='itinary_iti_region__5db7ce_idx'),
        ),
        migrations.AddIndex(
            model_name='itinary',
            index=models.Index(fields=['boundary'], name='itinary_iti_boundar_dc514b_idx'),
        ),
    ]
