# Generated by Django 5.1.2 on 2024-11-19 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinary', '0004_rename_geojson_area_itinary_boundary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinary',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
