# Generated by Django 5.1.2 on 2025-01-08 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinary', '0004_alter_itinary_block_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinary',
            name='metadata',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
