# Generated by Django 5.1.2 on 2025-03-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinary', '0005_itinary_metadata'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='itinary',
            index=models.Index(fields=['metadata'], name='itinary_iti_metadat_2a3a95_idx'),
        ),
    ]
