# Generated by Django 5.1.2 on 2024-11-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinary', '0005_alter_itinary_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinary',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
