# Generated by Django 5.1.2 on 2024-11-26 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinary', '0006_alter_itinary_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinary',
            options={'ordering': ['date_created']},
        ),
        migrations.AddField(
            model_name='itinary',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinary',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
