# Generated by Django 5.1.2 on 2025-03-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinary', '0006_itinary_itinary_iti_metadat_2a3a95_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinary',
            name='agency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
