# Generated by Django 5.1.2 on 2024-11-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinary', '0007_alter_itinary_options_itinary_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinary',
            options={'ordering': ['-date_created']},
        ),
    ]
