# Generated by Django 5.1.2 on 2024-11-14 08:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0002_region_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ona_token', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fields', models.TextField()),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='region.region')),
            ],
        ),
    ]
