# Generated by Django 5.1.2 on 2024-12-19 13:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ona_token', models.CharField()),
                ('fields', models.TextField()),
            ],
        ),
    ]
