# Generated by Django 5.1.2 on 2024-11-14 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('region', '0002_region_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='region',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='region.region'),
        ),
    ]
