# Generated by Django 5.1.2 on 2025-04-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_odkposition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odkposition',
            old_name='region',
            new_name='form_name',
        ),
        migrations.AddField(
            model_name='odkposition',
            name='form_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
