# Generated by Django 5.1.2 on 2024-11-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_formdata_region'),
        ('region', '0004_region_region_regi_name_df1a77_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='formdata',
            index=models.Index(fields=['region'], name='config_form_region__86294a_idx'),
        ),
    ]
