# Generated by Django 5.1.2 on 2024-11-19 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_formdata_config_form_region__86294a_idx'),
        ('record', '0010_alter_record_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='fields',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FormData',
        ),
    ]
