# Generated by Django 5.1.2 on 2025-04-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_rename_region_odkposition_form_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odkposition',
            old_name='form_id',
            new_name='project_id',
        ),
    ]
