# Generated by Django 5.1.2 on 2024-11-14 08:54

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('geojson_file', models.FileField(upload_to='geojson_files/')),
                ('geojson_area', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('geojson_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
