# Generated by Django 5.1.2 on 2024-11-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_region_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='geojson_file',
            field=models.FileField(blank=True, null=True, upload_to='geojson_files/'),
        ),
    ]
