# Generated by Django 5.1.2 on 2024-10-31 09:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_alter_location_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='location',
            name='area',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='location',
            name='geojson_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
