# Generated by Django 5.1.2 on 2024-10-31 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_remove_location_coordinates_location_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='area',
            new_name='geojson_area',
        ),
        migrations.AddField(
            model_name='location',
            name='geojson_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='geojson_files/'),
            preserve_default=False,
        ),
    ]
