# Generated by Django 5.1.2 on 2024-11-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_alter_region_geojson_file'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['name'], name='region_regi_name_df1a77_idx'),
        ),
    ]
