# Generated by Django 5.1.2 on 2024-11-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0004_region_region_regi_name_df1a77_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='geojson_area',
            new_name='boundary',
        ),
        migrations.RemoveField(
            model_name='region',
            name='geojson_content',
        ),
        migrations.RemoveField(
            model_name='region',
            name='geojson_file',
        ),
        migrations.AddField(
            model_name='region',
            name='ona_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['ona_name'], name='region_regi_ona_nam_2b6959_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['boundary'], name='region_regi_boundar_31425e_idx'),
        ),
    ]
