# Generated by Django 5.1.2 on 2024-11-01 07:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0004_rename_area_location_geojson_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geojson_area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
