# Generated by Django 5.1.2 on 2024-11-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0005_rename_geojson_area_region_boundary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='ona_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
