# Generated by Django 5.1.2 on 2024-11-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0006_alter_region_name_alter_region_ona_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
