# Generated by Django 5.1.2 on 2024-11-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0007_alter_region_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='region',
            name='region_regi_boundar_31425e_idx',
        ),
        migrations.RemoveField(
            model_name='region',
            name='boundary',
        ),
    ]
