# Generated by Django 5.1.2 on 2024-11-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0008_remove_region_region_regi_boundar_31425e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
