# Generated by Django 5.1.2 on 2024-11-26 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0009_alter_region_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 12, 53, 20, 586110, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
