# Generated by Django 5.1.2 on 2024-12-16 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0010_region_date_created_region_date_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='supervisor',
            field=models.ManyToManyField(blank=True, default=None, related_name='region', to=settings.AUTH_USER_MODEL),
        ),
    ]
