# Generated by Django 5.1.2 on 2025-03-26 11:47

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itinary', '0007_itinary_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_created'],
                'indexes': [models.Index(fields=['name'], name='record_acti_name_6e99d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('matricule', models.CharField(default='', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_created'],
                'indexes': [models.Index(fields=['name'], name='record_coll_name_e1c531_idx')],
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_created'],
                'indexes': [models.Index(fields=['name'], name='record_ente_name_1fa456_idx')],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ona_id', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('contrat', models.CharField(db_index=True, default='', max_length=100)),
                ('amount', models.CharField(db_index=True, default='', max_length=100)),
                ('accessibility', models.CharField(db_index=True, default='', max_length=100)),
                ('code_anomaly', models.CharField(db_index=True, default='', max_length=100)),
                ('sealed_number', models.CharField(db_index=True, default='', max_length=100)),
                ('cut_action', models.CharField(db_index=True, default='', max_length=100)),
                ('delivery_points', models.PositiveIntegerField(db_index=True, default=0)),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='record.action')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='record.collector')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='record.enterprise')),
                ('itinary', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='itinary.itinary')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='record.record')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, default='', max_length=100)),
                ('reason', models.CharField(db_index=True, default='', max_length=100)),
                ('status', models.CharField(db_index=True, default='', max_length=100)),
                ('activite', models.CharField(db_index=True, default='', max_length=100)),
                ('batiment', models.CharField(db_index=True, default='', max_length=100)),
                ('code_bare', models.CharField(db_index=True, default='', max_length=100, unique=True)),
                ('serial_number', models.CharField(db_index=True, default='', max_length=100, unique=True)),
                ('image_url', models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pl', to='record.record')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['itinary'], name='record_reco_itinary_daa5c1_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['ona_id'], name='record_reco_ona_id_01d75b_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['action'], name='record_reco_action__b4be56_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['collector'], name='record_reco_collect_16278b_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['enterprise'], name='record_reco_enterpr_83a3aa_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['contrat'], name='record_reco_contrat_2e0cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['amount'], name='record_reco_amount_dfb23b_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['accessibility'], name='record_reco_accessi_1aa4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['code_anomaly'], name='record_reco_code_an_bd9774_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['sealed_number'], name='record_reco_sealed__4c7099_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['cut_action'], name='record_reco_cut_act_67ab9c_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['delivery_points'], name='record_reco_deliver_8b932f_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['record'], name='record_loca_record__23837d_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['coordinates'], name='record_loca_coordin_ba397f_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypoint',
            index=models.Index(fields=['type'], name='record_deli_type_844f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypoint',
            index=models.Index(fields=['status'], name='record_deli_status_7ae0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypoint',
            index=models.Index(fields=['activite'], name='record_deli_activit_931eda_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypoint',
            index=models.Index(fields=['batiment'], name='record_deli_batimen_ec9952_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypoint',
            index=models.Index(fields=['code_bare'], name='record_deli_code_ba_8b0e82_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypoint',
            index=models.Index(fields=['image_url'], name='record_deli_image_u_0d88e8_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypoint',
            index=models.Index(fields=['serial_number'], name='record_deli_serial__253805_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypoint',
            index=models.Index(fields=['record'], name='record_deli_record__468239_idx'),
        ),
    ]
