# Generated by Django 5.1.2 on 2024-12-19 13:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itinary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_created'],
                'indexes': [models.Index(fields=['name'], name='record_acti_name_6e99d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_created'],
                'indexes': [models.Index(fields=['name'], name='record_coll_name_e1c531_idx')],
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_created'],
                'indexes': [models.Index(fields=['name'], name='record_ente_name_1fa456_idx')],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ona_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('data', models.TextField()),
                ('full_data', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='record.action')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='record.collector')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='record.enterprise')),
                ('itinary', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='itinary.itinary')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['itinary'], name='record_reco_itinary_daa5c1_idx'), models.Index(fields=['ona_id'], name='record_reco_ona_id_01d75b_idx'), models.Index(fields=['action'], name='record_reco_action__b4be56_idx'), models.Index(fields=['collector'], name='record_reco_collect_16278b_idx'), models.Index(fields=['enterprise'], name='record_reco_enterpr_83a3aa_idx'), models.Index(fields=['date'], name='record_reco_date_46564a_idx')],
            },
        ),
    ]
