# Generated by Django 5.1.2 on 2024-11-14 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='collector',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='enterprise',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
