# Generated by Django 5.1.2 on 2025-05-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypoint',
            name='activite',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='batiment',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='code_bare',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='contrat',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='index',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='reason',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='serial_number',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='status',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='thread_nbr',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='type',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='accessibility',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='amount',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='code_anomaly',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='contrat',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='cut_action',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='depart',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='depart_code',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='depart_nbr',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='existence',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='i1_input',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='i1_output',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='i2_input',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='i2_output',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='i3_input',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='i3_output',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='i4_input',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='i4_output',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='lighting',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='poste',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='poste_type',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='quality',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='sealed_number',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='source',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='record',
            name='telephone',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
    ]
