# Generated by Django 5.1.2 on 2025-03-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypoint',
            name='code_bare',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='serial_number',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
