# Generated by Django 5.1.2 on 2025-01-16 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='full_data',
        ),
        migrations.AlterField(
            model_name='record',
            name='data',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='record',
            name='ona_id',
            field=models.CharField(db_index=True, editable=False, max_length=100, unique=True),
        ),
    ]
