# Generated by Django 5.1.2 on 2025-06-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_alter_deliverypoint_activite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='banoc_code',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
    ]
