# Generated by Django 5.1.2 on 2025-01-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinary', '0005_itinary_metadata'),
        ('record', '0002_remove_record_full_data_alter_record_data_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['data'], name='record_reco_data_76eda9_idx'),
        ),
    ]
