# Generated by Django 5.1.2 on 2025-04-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_alter_deliverypoint_code_bare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypoint',
            name='index',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deliverypoint',
            name='thread_nbr',
            field=models.PositiveBigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='depart',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='depart_code',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='depart_nbr',
            field=models.PositiveBigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='existence',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='i1_input',
            field=models.CharField(db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='i1_output',
            field=models.CharField(db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='i2_input',
            field=models.CharField(db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='i2_output',
            field=models.CharField(db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='i3_input',
            field=models.CharField(db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='i3_output',
            field=models.CharField(db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='i4_input',
            field=models.CharField(db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='i4_output',
            field=models.CharField(db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='lighting',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='poste',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='poste_image_url',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='poste_type',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='quality',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='source',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='telephone',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
