# Generated by Django 5.1.2 on 2024-11-14 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_record_collector_record_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='action',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
