# Generated by Django 5.1.2 on 2024-11-14 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_record_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='ona_id',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
