# Generated by Django 5.1.2 on 2025-04-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_deliverypoint_index_deliverypoint_thread_nbr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypoint',
            name='contrat',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
