# Generated by Django 5.1.2 on 2025-03-24 09:37

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinary', '0007_itinary_agency'),
        ('record', '0003_record_record_reco_data_76eda9_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, default='', max_length=100)),
                ('status', models.CharField(db_index=True, default='', max_length=100)),
                ('activite', models.CharField(db_index=True, default='', max_length=100)),
                ('batiment', models.CharField(db_index=True, default='', max_length=100)),
                ('code_bare', models.CharField(db_index=True, default='', max_length=100)),
                ('serial_number', models.CharField(db_index=True, default='', max_length=100)),
                ('image_url', models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='record',
            name='record_reco_date_46564a_idx',
        ),
        migrations.RemoveIndex(
            model_name='record',
            name='record_reco_data_76eda9_idx',
        ),
        migrations.RemoveField(
            model_name='record',
            name='data',
        ),
        migrations.AddField(
            model_name='collector',
            name='matricule',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='accessibility',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='amount',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='code_anomaly',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='contrat',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='cut_action',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='delivery_points',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='sealed_number',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['contrat'], name='record_reco_contrat_2e0cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['amount'], name='record_reco_amount_dfb23b_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['accessibility'], name='record_reco_accessi_1aa4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['code_anomaly'], name='record_reco_code_an_bd9774_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['sealed_number'], name='record_reco_sealed__4c7099_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['cut_action'], name='record_reco_cut_act_67ab9c_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['delivery_points'], name='record_reco_deliver_8b932f_idx'),
        ),
        migrations.AddField(
            model_name='deliverypoint',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='record.record'),
        ),
        migrations.AddField(
            model_name='location',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='record.record'),
        ),
        migrations.AddIndex(
            model_name='deliverypoint',
            index=models.Index(fields=['type'], name='record_deli_type_844f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypoint',
            index=models.Index(fields=['status'], name='record_deli_status_7ae0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypoint',
            index=models.Index(fields=['activite'], name='record_deli_activit_931eda_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypoint',
            index=models.Index(fields=['batiment'], name='record_deli_batimen_ec9952_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypoint',
            index=models.Index(fields=['code_bare'], name='record_deli_code_ba_8b0e82_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypoint',
            index=models.Index(fields=['image_url'], name='record_deli_image_u_0d88e8_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypoint',
            index=models.Index(fields=['serial_number'], name='record_deli_serial__253805_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypoint',
            index=models.Index(fields=['record'], name='record_deli_record__468239_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['record'], name='record_loca_record__23837d_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['coordinates'], name='record_loca_coordin_ba397f_idx'),
        ),
    ]
