# Generated by Django 5.1.2 on 2024-11-14 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_record_ona_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 14, 13, 36, 18, 661791)),
        ),
    ]
