# Generated by Django 5.1.2 on 2025-04-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_deliverypoint_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypoint',
            name='image_url',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='poste_image_url',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
    ]
