# Generated by Django 5.1.2 on 2025-04-13 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_deliverypoint_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypoint',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pl', to='record.record'),
        ),
        migrations.AlterField(
            model_name='location',
            name='record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='record.record'),
        ),
    ]
