# Generated by Django 5.1.2 on 2024-11-14 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 14, 12, 38, 26, 126430, tzinfo=datetime.timezone.utc)),
        ),
    ]
