# Generated by Django 5.1.2 on 2025-03-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_deliverypoint_record_alter_location_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypoint',
            name='code_bare',
            field=models.CharField(db_index=True, default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='serial_number',
            field=models.CharField(db_index=True, default='', max_length=100, unique=True),
        ),
    ]
