# Generated by Django 5.1.2 on 2025-04-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_alter_deliverypoint_record_alter_location_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypoint',
            name='thread_nbr',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='depart_nbr',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
