# Generated by Django 5.1.2 on 2025-04-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_alter_deliverypoint_thread_nbr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='i1_input',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='i1_output',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='i2_input',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='i2_output',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='i3_input',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='i3_output',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='i4_input',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='i4_output',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
