# Generated by Django 5.1.2 on 2024-11-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_formdata_config_form_region__86294a_idx'),
        ('record', '0007_alter_record_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['form'], name='record_reco_form_id_c88e81_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['ona_id'], name='record_reco_ona_id_01d75b_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['action'], name='record_reco_action_24607a_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['collector'], name='record_reco_collect_9e632f_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['enterprise'], name='record_reco_enterpr_1fc3a3_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['date'], name='record_reco_date_46564a_idx'),
        ),
    ]
