# Generated by Django 5.1.2 on 2024-11-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_record_record_reco_form_id_c88e81_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['date']},
        ),
    ]
