# Generated by Django 5.1.2 on 2024-11-19 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_alter_record_options'),
        ('region', '0005_rename_geojson_area_region_boundary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='region.region'),
        ),
    ]
