# Generated by Django 5.1.2 on 2024-11-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_alter_record_form'),
        ('region', '0009_alter_region_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='record',
            name='record_reco_form_id_c88e81_idx',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='form',
            new_name='region',
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['region'], name='record_reco_region__1f318b_idx'),
        ),
    ]
