# Generated by Django 5.1.2 on 2024-11-19 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinary', '0006_alter_itinary_name'),
        ('record', '0011_remove_record_record_reco_form_id_c88e81_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='record',
            name='record_reco_region__1f318b_idx',
        ),
        migrations.RemoveField(
            model_name='record',
            name='region',
        ),
        migrations.AddField(
            model_name='record',
            name='itinary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='itinary.itinary'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['itinary'], name='record_reco_itinary_daa5c1_idx'),
        ),
    ]
