# Generated by Django 5.1.2 on 2024-11-26 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_remove_record_record_reco_region__1f318b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
