# Generated by Django 5.1.2 on 2024-12-02 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0013_record_date_created_record_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.RenameIndex(
            model_name='record',
            new_name='record_reco_action__b4be56_idx',
            old_name='record_reco_action_24607a_idx',
        ),
        migrations.RenameIndex(
            model_name='record',
            new_name='record_reco_collect_16278b_idx',
            old_name='record_reco_collect_9e632f_idx',
        ),
        migrations.RenameIndex(
            model_name='record',
            new_name='record_reco_enterpr_83a3aa_idx',
            old_name='record_reco_enterpr_1fc3a3_idx',
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['name'], name='record_acti_name_6e99d0_idx'),
        ),
        migrations.AlterField(
            model_name='record',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='record.action'),
        ),
        migrations.AddIndex(
            model_name='collector',
            index=models.Index(fields=['name'], name='record_coll_name_e1c531_idx'),
        ),
        migrations.AlterField(
            model_name='record',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='record.collector'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['name'], name='record_ente_name_1fa456_idx'),
        ),
        migrations.AlterField(
            model_name='record',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='record.enterprise'),
        ),
    ]
