# Generated by Django 5.1.2 on 2024-12-03 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinary', '0008_alter_itinary_options'),
        ('record', '0014_action_collector_enterprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='itinary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='itinary.itinary'),
        ),
    ]
