# Generated by Django 5.1.2 on 2024-12-16 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0015_alter_record_itinary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('serial_number', models.CharField(default='', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='supervisor',
            field=models.ManyToManyField(blank=True, default=None, related_name='record', to='record.pl'),
        ),
    ]
