# Generated by Django 5.1.2 on 2024-12-11 10:10

import record.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinary', '0008_alter_itinary_options'),
        ('record', '0015_alter_record_itinary'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='record',
            index=models.Index(record.models.MD5('data'), name='record_record_data_hash_idx'),
        ),
    ]
