# Generated by Django 5.1.2 on 2024-12-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0016_pl_record_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='record',
            name='pl',
            field=models.ManyToManyField(blank=True, default=None, related_name='records', to='record.pl'),
        ),
    ]
