# Generated by Django 5.1.2 on 2024-12-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0016_record_record_record_data_hash_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='record',
            name='record_record_data_hash_idx',
        ),
    ]
