# Generated by Django 5.1.2 on 2024-12-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0017_remove_record_supervisor_record_pl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='pl',
        ),
    ]
