# Generated by Django 5.1.2 on 2024-12-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0018_remove_record_pl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pl',
        ),
    ]
