# Generated by Django 5.1.2 on 2024-12-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0019_delete_pl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-date']},
        ),
    ]
